// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlng3JovlLwKdJ3rDJbg4geYK-tIwT1pk',
    appId: '1:902441054407:web:f66c5b95b728233d4acee2',
    messagingSenderId: '902441054407',
    projectId: 'pulse-c7c16',
    authDomain: 'pulse-c7c16.firebaseapp.com',
    storageBucket: 'pulse-c7c16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjvlw2zHXfnq3odN5o8-9r7nHGisI7Mo',
    appId: '1:902441054407:android:2571be8cb841e3434acee2',
    messagingSenderId: '902441054407',
    projectId: 'pulse-c7c16',
    storageBucket: 'pulse-c7c16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdLiFe_--muID6QkuIpzjTi6Pg0zKYIs',
    appId: '1:902441054407:ios:579399abbd04250d4acee2',
    messagingSenderId: '902441054407',
    projectId: 'pulse-c7c16',
    storageBucket: 'pulse-c7c16.appspot.com',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHdLiFe_--muID6QkuIpzjTi6Pg0zKYIs',
    appId: '1:902441054407:ios:579399abbd04250d4acee2',
    messagingSenderId: '902441054407',
    projectId: 'pulse-c7c16',
    storageBucket: 'pulse-c7c16.appspot.com',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlng3JovlLwKdJ3rDJbg4geYK-tIwT1pk',
    appId: '1:902441054407:web:fb651e48c84c7e254acee2',
    messagingSenderId: '902441054407',
    projectId: 'pulse-c7c16',
    authDomain: 'pulse-c7c16.firebaseapp.com',
    storageBucket: 'pulse-c7c16.appspot.com',
  );
}
